<?php
/**
 * PermitUserGroupRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Gopad
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gopad OpenAPI
 *
 * API definition for Gopad, Etherpad for markdown with go
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: gopad@webhippie.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Gopad\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PermitUserGroupRequestTest Class Doc Comment
 *
 * @category    Class
 * @description PermitUserGroupRequest
 * @package     Gopad
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PermitUserGroupRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PermitUserGroupRequest"
     */
    public function testPermitUserGroupRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "perm"
     */
    public function testPropertyPerm()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
