<?php
/**
 * AuthApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Gopad
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gopad OpenAPI
 *
 * API definition for Gopad, Etherpad for markdown with go
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: gopad@webhippie.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Gopad\Test\Api;

use \Gopad\Configuration;
use \Gopad\ApiException;
use \Gopad\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AuthApiTest Class Doc Comment
 *
 * @category Class
 * @package  Gopad
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuthApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for callbackProvider
     *
     * Callback to parse the defined provider.
     *
     */
    public function testCallbackProvider()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listProviders
     *
     * Fetch the available auth providers.
     *
     */
    public function testListProviders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for loginAuth
     *
     * Authenticate an user by credentials.
     *
     */
    public function testLoginAuth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for refreshAuth
     *
     * Refresh an auth token before it expires.
     *
     */
    public function testRefreshAuth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestProvider
     *
     * Request the redirect to defined provider.
     *
     */
    public function testRequestProvider()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verifyAuth
     *
     * Verify validity for an authentication token.
     *
     */
    public function testVerifyAuth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
