<?php
/**
 * GroupApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Gopad
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gopad OpenAPI
 *
 * API definition for Gopad, Etherpad for markdown with go
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: gopad@webhippie.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Gopad\Test\Api;

use \Gopad\Configuration;
use \Gopad\ApiException;
use \Gopad\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GroupApiTest Class Doc Comment
 *
 * @category Class
 * @package  Gopad
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GroupApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for attachGroupToUser
     *
     * Attach a user to group.
     *
     */
    public function testAttachGroupToUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createGroup
     *
     * Create a new group.
     *
     */
    public function testCreateGroup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteGroup
     *
     * Delete a specific group.
     *
     */
    public function testDeleteGroup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteGroupFromUser
     *
     * Unlink a user from group.
     *
     */
    public function testDeleteGroupFromUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listGroupUsers
     *
     * Fetch all users attached to group.
     *
     */
    public function testListGroupUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listGroups
     *
     * Fetch all available groups.
     *
     */
    public function testListGroups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for permitGroupUser
     *
     * Update user perms for group.
     *
     */
    public function testPermitGroupUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for showGroup
     *
     * Fetch a specific group.
     *
     */
    public function testShowGroup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateGroup
     *
     * Update a specific group.
     *
     */
    public function testUpdateGroup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
