<?php
/**
 * TeamApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Gopad
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gopad OpenAPI
 *
 * API definition for Gopad, Etherpad for markdown with go
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: gopad@webhippie.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Gopad\Test\Api;

use \Gopad\Configuration;
use \Gopad\ApiException;
use \Gopad\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TeamApiTest Class Doc Comment
 *
 * @category Class
 * @package  Gopad
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TeamApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for attachTeamToUser
     *
     * Assign a user to team.
     *
     */
    public function testAttachTeamToUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createTeam
     *
     * Create a new team.
     *
     */
    public function testCreateTeam()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteTeam
     *
     * Delete a specific team.
     *
     */
    public function testDeleteTeam()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteTeamFromUser
     *
     * Remove a user from team.
     *
     */
    public function testDeleteTeamFromUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listTeamUsers
     *
     * Fetch all users assigned to team.
     *
     */
    public function testListTeamUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listTeams
     *
     * Fetch all available teams.
     *
     */
    public function testListTeams()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for permitTeamUser
     *
     * Update user perms for team.
     *
     */
    public function testPermitTeamUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for showTeam
     *
     * Fetch a specific team.
     *
     */
    public function testShowTeam()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateTeam
     *
     * Update a specific team.
     *
     */
    public function testUpdateTeam()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
